/** 
 *  Generated by OpenJPA MetaModel Generator Tool.
**/

package model.database.jpa.tables;

import javax.persistence.metamodel.SingularAttribute;

@javax.persistence.metamodel.StaticMetamodel
(value=model.database.jpa.tables.AlgorithmSettingDouble.class)
@javax.annotation.Generated
(value="org.apache.openjpa.persistence.meta.AnnotationProcessor6",date="Wed May 16 20:21:34 CEST 2012")
public class AlgorithmSettingDouble_ {
    public static volatile SingularAttribute<AlgorithmSettingDouble,Double> defaultValue; //NOPMD
    public static volatile SingularAttribute<AlgorithmSettingDouble,Double> maxValue; //NOPMD
    public static volatile SingularAttribute<AlgorithmSettingDouble,Double> minValue; //NOPMD
    public static volatile SingularAttribute<AlgorithmSettingDouble,String> name; //NOPMD
    public static volatile SingularAttribute<AlgorithmSettingDouble,Integer> settingIndex; //NOPMD
    public static volatile SingularAttribute<AlgorithmSettingDouble,String> settingText; //NOPMD
    public static volatile SingularAttribute<AlgorithmSettingDouble,Double> value; //NOPMD
}
