/** 
 *  Generated by OpenJPA MetaModel Generator Tool.
**/

package model.database.jpa.tables;

import javax.persistence.metamodel.SingularAttribute;

@javax.persistence.metamodel.StaticMetamodel
(value=model.database.jpa.tables.AlgorithmSettingLong.class)
@javax.annotation.Generated
(value="org.apache.openjpa.persistence.meta.AnnotationProcessor6",date="Wed May 16 20:21:34 CEST 2012")
public class AlgorithmSettingLong_ {
    public static volatile SingularAttribute<AlgorithmSettingLong,Long> defaultValue; //NOPMD
    public static volatile SingularAttribute<AlgorithmSettingLong,Long> maxValue; //NOPMD
    public static volatile SingularAttribute<AlgorithmSettingLong,Long> minValue; //NOPMD
    public static volatile SingularAttribute<AlgorithmSettingLong,String> name; //NOPMD
    public static volatile SingularAttribute<AlgorithmSettingLong,Integer> settingIndex; //NOPMD
    public static volatile SingularAttribute<AlgorithmSettingLong,String> settingText; //NOPMD
    public static volatile SingularAttribute<AlgorithmSettingLong,Long> value; //NOPMD
}
