/** 
 *  Generated by OpenJPA MetaModel Generator Tool.
**/

package model.database.jpa.tables;

import javax.persistence.metamodel.ListAttribute;
import javax.persistence.metamodel.SingularAttribute;

@javax.persistence.metamodel.StaticMetamodel
(value=model.database.jpa.tables.PortfolioEntity.class)
@javax.annotation.Generated
(value="org.apache.openjpa.persistence.meta.AnnotationProcessor6",date="Wed May 16 20:21:34 CEST 2012")
public class PortfolioEntity_ {
    public static volatile SingularAttribute<PortfolioEntity,AlgorithmSettings> algorithmSettings; //NOPMD
    public static volatile SingularAttribute<PortfolioEntity,Long> balance; //NOPMD
    public static volatile ListAttribute<PortfolioEntity,PortfolioHistory> history; //NOPMD
    public static volatile ListAttribute<PortfolioEntity,PortfolioInvestment> investments; //NOPMD
    public static volatile SingularAttribute<PortfolioEntity,String> name; //NOPMD
    public static volatile SingularAttribute<PortfolioEntity,Integer> portfolioId; //NOPMD
    public static volatile SingularAttribute<PortfolioEntity,Boolean> stopBuying; //NOPMD
    public static volatile SingularAttribute<PortfolioEntity,Boolean> stopSelling; //NOPMD
    public static volatile SingularAttribute<PortfolioEntity,Boolean> watchAllStocks; //NOPMD
}
