/** 
 *  Generated by OpenJPA MetaModel Generator Tool.
**/

package model.database.jpa.tables;

import javax.persistence.metamodel.ListAttribute;
import javax.persistence.metamodel.SingularAttribute;

@javax.persistence.metamodel.StaticMetamodel
(value=model.database.jpa.tables.AlgorithmSettings.class)
@javax.annotation.Generated
(value="org.apache.openjpa.persistence.meta.AnnotationProcessor6",date="Thu May 03 20:24:15 CEST 2012")
public class AlgorithmSettings_ {
    public static volatile SingularAttribute<AlgorithmSettings,String> algorithmName;
    public static volatile ListAttribute<AlgorithmSettings,AlgorithmSettingDouble> doubleSettings;
    public static volatile SingularAttribute<AlgorithmSettings,Boolean> initiated;
    public static volatile ListAttribute<AlgorithmSettings,AlgorithmSettingLong> longSettings;
}
