/** 
 *  Generated by OpenJPA MetaModel Generator Tool.
**/

package model.database.jpa.tables;

import javax.persistence.metamodel.SingularAttribute;

@javax.persistence.metamodel.StaticMetamodel
(value=model.database.jpa.tables.AlgorithmSettingLong.class)
@javax.annotation.Generated
(value="org.apache.openjpa.persistence.meta.AnnotationProcessor6",date="Thu May 03 20:24:15 CEST 2012")
public class AlgorithmSettingLong_ {
    public static volatile SingularAttribute<AlgorithmSettingLong,Long> defaultValue;
    public static volatile SingularAttribute<AlgorithmSettingLong,Long> maxValue;
    public static volatile SingularAttribute<AlgorithmSettingLong,Long> minValue;
    public static volatile SingularAttribute<AlgorithmSettingLong,String> name;
    public static volatile SingularAttribute<AlgorithmSettingLong,Integer> settingIndex;
    public static volatile SingularAttribute<AlgorithmSettingLong,String> settingText;
    public static volatile SingularAttribute<AlgorithmSettingLong,Long> value;
}
