/** 
 *  Generated by OpenJPA MetaModel Generator Tool.
**/

package model.database.jpa.tables;

import javax.persistence.metamodel.SingularAttribute;

@javax.persistence.metamodel.StaticMetamodel
(value=model.database.jpa.tables.AlgorithmSettingDouble.class)
@javax.annotation.Generated
(value="org.apache.openjpa.persistence.meta.AnnotationProcessor6",date="Wed May 16 20:21:34 CEST 2012")
public class AlgorithmSettingDouble_ {
    public static volatile SingularAttribute<AlgorithmSettingDouble,Double> defaultValue;
    public static volatile SingularAttribute<AlgorithmSettingDouble,Double> maxValue;
    public static volatile SingularAttribute<AlgorithmSettingDouble,Double> minValue;
    public static volatile SingularAttribute<AlgorithmSettingDouble,String> name;
    public static volatile SingularAttribute<AlgorithmSettingDouble,Integer> settingIndex;
    public static volatile SingularAttribute<AlgorithmSettingDouble,String> settingText;
    public static volatile SingularAttribute<AlgorithmSettingDouble,Double> value;
}
